version: "2"

services:
  web:
    image: php:7.0-apache
    restart: always
    environment: 
      DEV_DB_HOST: db:3306
      DEV_DB_PASSWORD: webshop
    ports:
      - "8080:80"
    volumes:
     - ./src:/var/www/html
    depends_on:
     - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: webshop 
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshop
      MYSQL_PASSWORD: webshop
